// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2012.2
// Copyright (C) 2012 Xilinx Inc. All rights reserved.
// 
// ==============================================================


module count_horiz_grp_fu_2704_ACMP_mul_1_MulnS_0(clk, ce, a, b, p);
input clk;
input ce;
input[4 - 1 : 0] a; // synthesis attribute keep a "true"
input[4 - 1 : 0] b; // synthesis attribute keep b "true"
output[7 - 1 : 0] p;
reg[4 - 1 : 0] a_reg;
reg[4 - 1 : 0] b_reg;
wire [7 - 1 : 0] tmp_product;
reg[7 - 1 : 0] buff0;

assign p = buff0;
assign tmp_product = a_reg * b_reg;
always @ (posedge clk) begin
    if (ce) begin
        a_reg <= a;
        b_reg <= b;
        buff0 <= tmp_product;
    end
end
endmodule
