// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2012.2
// Copyright (C) 2012 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xgenerate_board_counts.h"

/************************** Function Implementation *************************/
int XGenerate_board_counts_Initialize(XGenerate_board_counts *InstancePtr, XGenerate_board_counts_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_BaseAddress = ConfigPtr->Ctrl_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}

void XGenerate_board_counts_Start(XGenerate_board_counts *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGenerate_board_counts_WriteReg(InstancePtr->Ctrl_BaseAddress, XGENERATE_BOARD_COUNTS_CTRL_ADDR_AP_CTRL, 1);
}

u32 XGenerate_board_counts_IsDone(XGenerate_board_counts *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGenerate_board_counts_ReadReg(InstancePtr->Ctrl_BaseAddress, XGENERATE_BOARD_COUNTS_CTRL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XGenerate_board_counts_IsIdle(XGenerate_board_counts *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGenerate_board_counts_ReadReg(InstancePtr->Ctrl_BaseAddress, XGENERATE_BOARD_COUNTS_CTRL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

void XGenerate_board_counts_SetBoard_addr(XGenerate_board_counts *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGenerate_board_counts_WriteReg(InstancePtr->Ctrl_BaseAddress, XGENERATE_BOARD_COUNTS_CTRL_ADDR_BOARD_ADDR_DATA, Data);
}

u32 XGenerate_board_counts_GetBoard_addr(XGenerate_board_counts *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGenerate_board_counts_ReadReg(InstancePtr->Ctrl_BaseAddress, XGENERATE_BOARD_COUNTS_CTRL_ADDR_BOARD_ADDR_DATA);
    return Data;
}

void XGenerate_board_counts_SetResult_addr(XGenerate_board_counts *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGenerate_board_counts_WriteReg(InstancePtr->Ctrl_BaseAddress, XGENERATE_BOARD_COUNTS_CTRL_ADDR_RESULT_ADDR_DATA, Data);
}

u32 XGenerate_board_counts_GetResult_addr(XGenerate_board_counts *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGenerate_board_counts_ReadReg(InstancePtr->Ctrl_BaseAddress, XGENERATE_BOARD_COUNTS_CTRL_ADDR_RESULT_ADDR_DATA);
    return Data;
}

void XGenerate_board_counts_InterruptGlobalEnable(XGenerate_board_counts *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGenerate_board_counts_WriteReg(InstancePtr->Ctrl_BaseAddress, XGENERATE_BOARD_COUNTS_CTRL_ADDR_GIE, 1);
}

void XGenerate_board_counts_InterruptGlobalDisable(XGenerate_board_counts *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGenerate_board_counts_WriteReg(InstancePtr->Ctrl_BaseAddress, XGENERATE_BOARD_COUNTS_CTRL_ADDR_GIE, 0);
}

void XGenerate_board_counts_InterruptEnable(XGenerate_board_counts *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XGenerate_board_counts_ReadReg(InstancePtr->Ctrl_BaseAddress, XGENERATE_BOARD_COUNTS_CTRL_ADDR_IER);
    XGenerate_board_counts_WriteReg(InstancePtr->Ctrl_BaseAddress, XGENERATE_BOARD_COUNTS_CTRL_ADDR_IER, Register | Mask);
}

void XGenerate_board_counts_InterruptDisable(XGenerate_board_counts *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XGenerate_board_counts_ReadReg(InstancePtr->Ctrl_BaseAddress, XGENERATE_BOARD_COUNTS_CTRL_ADDR_IER);
    XGenerate_board_counts_WriteReg(InstancePtr->Ctrl_BaseAddress, XGENERATE_BOARD_COUNTS_CTRL_ADDR_IER, Register & (~Mask));
}

void XGenerate_board_counts_InterruptClear(XGenerate_board_counts *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XGenerate_board_counts_ReadReg(InstancePtr->Ctrl_BaseAddress, XGENERATE_BOARD_COUNTS_CTRL_ADDR_ISR);
    XGenerate_board_counts_WriteReg(InstancePtr->Ctrl_BaseAddress, XGENERATE_BOARD_COUNTS_CTRL_ADDR_ISR, Register & Mask);
}

u32 XGenerate_board_counts_InterruptGetEnabled(XGenerate_board_counts *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XGenerate_board_counts_ReadReg(InstancePtr->Ctrl_BaseAddress, XGENERATE_BOARD_COUNTS_CTRL_ADDR_IER);
}

u32 XGenerate_board_counts_InterruptGetStatus(XGenerate_board_counts *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XGenerate_board_counts_ReadReg(InstancePtr->Ctrl_BaseAddress, XGENERATE_BOARD_COUNTS_CTRL_ADDR_ISR);
}

