
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.2 EDK_P.28xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "touchsensor.h"

/*
* The configuration table for devices
*/

TouchSensor_Config TouchSensor_ConfigTable[] =
{
	{
		XPAR_TOUCHSENSOR_0_DEVICE_ID,
		XPAR_TOUCHSENSOR_0_BASEADDR,
		XPAR_TOUCHSENSOR_0_HIGHADDR
	}
};


